name: build

on:
  push:
    branches: [ master ]

jobs:
  build-builder:
    name: "Build docker builder"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          file: build/ubuntu-focal/Dockerfile

          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: pgx-ubuntu-focal-amd64:latest
          outputs: type=docker,dest=/tmp/builder.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: builder
          path: /tmp/builder.tar

  build-ext:
    name: "Build extension binaries"
    needs: build-builder
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 11, 12, 13, 14, 15 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: builder
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/builder.tar
          docker image ls -a

      - name: run builder
        run: |
          mkdir -p artifacts
          docker run -v ${PWD}:/home/docker/pkg/:rw -v ${PWD}/artifacts:/artifacts:rw -e PG_VERSION=${{matrix.version}} pgx-ubuntu-focal-amd64:latest ./scripts/package.sh


      - name: Release
        uses: softprops/action-gh-release@v1
#        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: artifacts/*