name: build

on:
  push:

jobs:
  build-ext:
    name: "Build extension binaries"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 16
      matrix:
        version: [ 11, 12, 13, 14, 15 ]
        image:
          - debian-bullseye
          - debian-bookworm
          - ubuntu-focal
          - ubuntu-jammy
          - ubuntu-kinetic
          - fedora-36
          - fedora-37
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Prepare builder container
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          file: build/${{matrix.image}}/Dockerfile
          cache-from: type=gha,scope=build-${{matrix.image}}
          cache-to: type=gha,mode=max,scope=build-${{matrix.image}}
          tags: pgx-${{matrix.image}}-amd64:latest

      - name: Cache target directory
        uses: actions/cache@v3
        with:
          key: ${{matrix.image}}-pg${{matrix.version}}-${{hashFiles('Cargo.lock')}}
          path: target

      - name: Build extension
        run: |
          mkdir -p artifacts
          docker run -v ${PWD}:/home/docker/pkg/:rw -v ${PWD}/target:/home/docker/pkg/target:rw -v ${PWD}/artifacts:/artifacts:rw --user root:root -e PG_VERSION=${{matrix.version}} pgx-${{matrix.image}}-amd64:latest ./scripts/package.sh ${{matrix.image}}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: pg_url-${{matrix.image}}-pg${{matrix.version}}-amd64
          path: artifacts/

  release:
    name: "Release built extension binaries"
    needs: build-ext
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: List Files
        run: |
          ls artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/pg_url-*/**
          body: |
            See the [changelog]()